// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CSVEditor
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string ContentTypeString = "5b2dc8c1-5049-43fb-b02a-376196cec872";
        public static Guid ContentType = new Guid(ContentTypeString);

        public const string CSVEditorString = "55b9ed45-59d1-40dc-8003-343d792221d7";
        public static Guid CSVEditor = new Guid(CSVEditorString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int CsvContextMenuGroup = 0x0002;
        public const int GoToColumnCommand = 0x0105;
        public const int AlignColumnsCommand = 0x0101;
        public const int ShrinkColumnsCommand = 0x0102;
        public const int ToggleAlternateRowsCommand = 0x0103;
        public const int CopyAsMarkdownCommand = 0x0104;
        public const int ToggleStickyHeaderCommand = 0x0106;
    }
}
