// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the free extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
using System;

namespace CSVEditor
{
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string CSVEditorString = "55b9ed45-59d1-40dc-8003-343d792221d7";
        public static Guid CSVEditor = new Guid(CSVEditorString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int MyCommand = 0x0100;
    }
}
